# .github/workflows/tweet.yml

name: Daily Tech News Tweet

on:
  schedule:
    # Exécute tous les jours à 10h00, 16h00 et 22h00 UTC
    # Vous pouvez ajuster cela selon vos besoins
    - cron: '0 10,16,22 * * *' 
  workflow_dispatch: # Permet de déclencher le workflow manuellement depuis GitHub

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Utilise la dernière version de Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests tweepy python-dotenv # python-dotenv n'est pas utilisé directement ici mais utile pour le dev local

    - name: Run UrTechNews Twitter Bot
      env: # Définition des variables d'environnement SECURISEES
        MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: python ur_tech_news_bot.py
